server:
  port: 8011

eureka:
  instance:
    instance-id: manage-web-serviceId
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka
      
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:  Asia/Shanghai
    default-property-inclusion: non-null  #返回的字段为空的时候不返回该字段
  application:
    name: manage-web-service

  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 200

