server:
  port: 1002
security:
  user: 
    name: root
    password: root
    
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/wq_cms
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 200
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: auth/register

logging:
  config: classpath:logback.xml



