server:
  port: 8000
#redis 配置
spring:
  redis:
    database: 0  #使用的redis数据库的索引
    host: localhost #主机名
    port: 6379 #端口号
    password: #密码
    pool:
      max-active: 8 #连接池的最大连接数
      max-wait: -1  #连接最大阻塞时间,为-1表示无限制
      max-idle: 0  #连接池的最小的空闲连接
    timeout: 0 #连接超时时间